name: Generate Snake Contribution

on:
  schedule:
    - cron: "0 0 * * *" # todo dia à meia-noite UTC
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: clodomilson-silva
          outputs: |
            ./output/github-contribution-grid-snake.svg

      - name: Commit & Push
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions"
          git add output/github-contribution-grid-snake.svg
          git commit -m "Generated snake contribution grid" || echo "No changes to commit"
          git push https://clodomilson-silva:${{ secrets.PERSONAL_TOKEN }}@github.com/clodomilson-silva/clodomilson-silva.git HEAD:main
